### ISSUE TITLE
Morning session P2P CR

### ISSUE THREAD

**Issue by MMGGYY66** [SFarida/to-do-list#2]
# Highlights
- Well done. You did a great job so far.
- Your code is clean and organised.
- Using bootstrap is implemented properly

**Comment by gealsanchez** [comment]
# STATUS: APPROVED 🟢
## Hi @SFarida , 
![Congratulations!GIF](https://user-images.githubusercontent.com/55918904/191301390-43d62dfa-bfdc-49c5-943b-4d72f4ea5bb8.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- GitHub flow is used correctly. ✔
- All linters checks are ok. ✔

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [ ] [OPTIONAL]  To improve maintainability and readability it's better to style the elements in a separate CSS file instead of inline styles  :heavy_check_mark::smiley: 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the issue thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
